### ISSUE TITLE
Error in predicting using upload dataset

### ISSUE THREAD

**Issue by hsarimv** [KinkyDesign/JaqpotQuattroUI#21]
Received error when trying to predict using one of the reference metal oxide models

**Comment by hampos** [comment]
It is an API error, incompatibility between the existing models and changes in the source code. We will have to rebuild existing models to solve this.

**Comment by hampos** [comment]
MeOx models should work now, walkey with zeta potential transformations will work as soon as #25 is fixed.

**Comment by hampos** [comment]
walkey model with zp transformations now works
