### ISSUE TITLE
Error in create dataset

### ISSUE THREAD

**Issue by hsarimv** [KinkyDesign/JaqpotQuattroUI#29]
Used FCSV-681C8532-60A2-3D01-9E89-1591010B179A with all substances, all experimental values and only experimental data descriptors and received an error

**Comment by hampos** [comment]
Could you please provide a task id? Or a description of the error?
I can't seem to be able to reproduce the error.

**Comment by hampos** [comment]
Closing this, it appears a replicate of issue #18
