### ISSUE TITLE
Model validation fails

### ISSUE THREAD

**Issue by alphaville** [KinkyDesign/JaqpotQuattroUI#47]
Steps to reproduce the error:
- Go to test.jaqpot.org and log in as `guest`
- Browse to http://test.jaqpot.org/m_detail?name=acT3dxc3vB9Br0jvbSqZ
- Click on "Validate me"
- Select the first dataset (name: PVrY25q3vd5O)

I got an error message which you may find at http://dpaste.com/0XCA0T9

**Comment by hampos** [comment]
Tried the exact same thing and it succeeded, got a report:
http://test.jaqpot.org/report?name=LiR6hF2hWfO69i3

**Comment by alphaville** [comment]
Indeed, it works today. Is it possible that yesterday SSO was down? In any case, a better error message should be returned to the user. Can you dig into that [error report ](http://dpaste.com/0XCA0T9) and make something out of it?
