### ISSUE TITLE
Delete algorithms?

### ISSUE THREAD

**Issue by alphaville** [KinkyDesign/JaqpotQuattroUI#50]
The button "Delete" at an Algorithm page is visible to guest users. If clicked, it takes the user back to the main page and no error message is shown.

**Comment by hampos** [comment]
Were you able to delete the selected algorithm? Are you it's creator?

**Comment by alphaville** [comment]
@hampos No, I didn't delete the algorithm. But, I think that in such a case the "Delete" button shouldn't be visible and/or click-able, otherwise, an error message should be returned to the user rather than redirect them to the main page.
