### ISSUE TITLE
Task failed with insufficient information

### ISSUE THREAD

**Issue by alphaville** [KinkyDesign/JaqpotQuattroUI#53]
I tried to create a SVM model and the [corresponding task](http://test.jaqpot.org/t_detail?name=4GxTMJQMw2xa&status=queued) failed and returned an HTTP status 500 (code: InternalServerError) and error message

```
Index: 0, Size: 0 Details: JPDI Training procedure error
```

This is not very informative and the user cannot tell whether the training halted because of some missing value (in which case the HTTP status code should be 200) or for some other reason.

**Comment by hampos** [comment]
We are currently working on a mechanism that will validate the correctness of any request before initiating a task process, while returning a much more informative error message. This will not be included in the 4.0.1 release though.

**Comment by hampos** [comment]
ParameterValidator class by @AValsamis 
https://github.com/KinkyDesign/JaqpotQuattro/blob/master/JaqpotCoreServices/src/main/java/org/jaqpot/core/service/validator/ParameterValidator.java
Now validates the correctness of each training request according to the parameter spec of the chosen algorithm. If any violation is detected, a bad request response is issued before going to the task system.
