### ISSUE TITLE
Compounds in model predictions

### ISSUE THREAD

**Issue by alphaville** [KinkyDesign/JaqpotQuattroUI#54]
I performed some predictions using a model and I got this result:

http://test.jaqpot.org/predicted_dataset?name=v4ZeoBVVSfnxSQQeMMWu&model=mL09qKyqwszX

I think it would be useful if all compounds were click-able, because currently names like `G15.AC_1` aren't very informative.

**Comment by hsarimv** [comment]
same with issue 66
