### ISSUE TITLE
Time tags

### ISSUE THREAD

**Issue by hsarimv** [KinkyDesign/JaqpotQuattroUI#63]
It would be nice to have time tags in all resources and tasks, so that we can sort them accoriding to time

**Comment by hampos** [comment]
Most resources already have time tags, I will look into pre-sorting them server side.

**Comment by hampos** [comment]
All resources have time-tags now and are pre-sorted in descending date order.
Commit: https://github.com/KinkyDesign/JaqpotQuattro/commit/fccd8e31013ca10d845c3370c99b43f87a351a9a
