### ISSUE TITLE
Delete buttons allignement

### ISSUE THREAD

**Issue by hsarimv** [KinkyDesign/JaqpotQuattroUI#72]
After the addition of tha time tag, the delete button do not show well. They appear in an horizontal and not in a vertical fashion next to each item to be deleted

**Comment by gdrakakis** [comment]
![image](https://cloud.githubusercontent.com/assets/10755430/16840018/0e7a0af6-49db-11e6-886b-ca6dcb0851b4.png)

**Comment by hampos** [comment]
![1](https://cloud.githubusercontent.com/assets/176635/17019182/c582d94a-4f43-11e6-87a9-f52585f334a5.jpg)
![2](https://cloud.githubusercontent.com/assets/176635/17019188/cc74e40a-4f43-11e6-9229-c0dff19574cc.jpg)
![3](https://cloud.githubusercontent.com/assets/176635/17019194/d34ac434-4f43-11e6-88f3-d2b4fa5c365a.jpg)

**Comment by dphilip** [comment]
Looks messed on a 24 inch screen, but is fixed when I zoom out a little.

![screen shot 2016-07-22 at 12 50 37 pm](https://cloud.githubusercontent.com/assets/7021386/17053501/fafbf7d8-500a-11e6-9865-016ee4434ab5.png)
![screen shot 2016-07-22 at 12 50 46 pm](https://cloud.githubusercontent.com/assets/7021386/17053502/fb26fba4-500a-11e6-9908-485ec0ff2e61.png)
