### ISSUE TITLE
Training with a deficient dataset

### ISSUE THREAD

**Issue by AValsamis** [KinkyDesign/JaqpotQuattroUI#73]
When training a model with a dataset consisting of <2 rows, the procedure should never start (maybe introduce the logic in `parameter validation` of training procedure?

**Comment by hampos** [comment]
This check:

```
if (datasetMeta.getTotalRows()<2)
            throw new BadRequestException("Dataset should have more than 1 row for a meaningful prediction");
```

Should happen on `AlgorithmResource` in `trainModel()` method.
A prediction with a 1 row dataset is perfectly valid, a prediction with a 0 row dataset is even valid for some model cases.
