### ISSUE TITLE
Creating a dataset from a substanceowner with Images and PDB files

### ISSUE THREAD

**Issue by dphilip** [KinkyDesign/JaqpotQuattroUI#74]
While trying to create a dataset from a bundle with Images and PDB files, I noticed the following:

I input this substanceowner:
https://apps.ideaconsult.net/enmtest/substanceowner/XLSX-021e69c9-4fa3-3e1e-b2b7-871ceab93347 
to
http://jaqpot.org/substance
1.
When I request Image descriptors calculation, the task never finishes
http://jaqpot.org/t_detail?name=TSK0UiMOp6boFcD&status=running
1. When adding only Experimental data. Nanomaterial properties derived from experiments
   it finishes:
   http://jaqpot.org/t_detail?name=TSKrKuXg6v3RVbp&status=running
   but then I get a "Key error" 
   http://jaqpot.org/data_detail?name=RfbLMSC3fdXO

**Comment by dphilip** [comment]
Tried again with a dataset with only images:
https://apps.ideaconsult.net/enmtest/substanceowner/XLSX-87e4c0ee-496d-34ef-bea3-a800dd57af0d/dataset 
1.
Selecting all descriptors gives:
Error: Utterly unhandled exception. Unable to invoke request
2.
Selecting only the images leads to task
http://jaqpot.org/t_detail?name=TSKvkx5MaOtrmRU&status=running
3.
Selecting only the experimental ones leads to task
http://jaqpot.org/t_detail?name=TSKmCHOZxyu9Q3o&status=running
which completes and leads to https://apps.ideaconsult.net/enmtest/bundle/283, but clicking the link returns a Key error http://jaqpot.org/data_detail?name=MmMsFPPYEItI

**Comment by dphilip** [comment]
Inputting this
https://apps.ideaconsult.net/enmtest/substanceowner/XLSX-f66add42-650b-3374-b6fd-baa1df2dff1b
returns (with no details in the fields):
Error Message:

Error Details:

**Comment by hampos** [comment]
I have successfully uploaded ImageAnalysis new version on test.jaqpot.org
Please try again on that server and report any errors

**Comment by dphilip** [comment]
Using this https://apps.ideaconsult.net/enmtest/substanceowner/XLSX-f66add42-650b-3374-b6fd-baa1df2dff1b as input, leads to task http://test.jaqpot.org/t_detail?name=TSK2tImylSHfSNb&status=running, which completes but returns key error http://test.jaqpot.org/data_detail?name=aeYqNBilVlg5
The bundle is created, but it's empty: https://apps.ideaconsult.net/enmtest/bundle/289?media=application%2Fjson

**Comment by dphilip** [comment]
When selecting no descriptors, a key error is returned: http://test.jaqpot.org/data_detail?name=2UEm4xzHFtUH
(same when selecting only experimental descriptors)

**Comment by dphilip** [comment]
Uploaded a similar dataset, but without the InChi field: 
https://apps.ideaconsult.net/enmtest/substanceowner/XLSX-e9b1d504-f54c-3968-aa61-0f0824169760
Using this give an error: http://test.jaqpot.org/data_detail?name=HQ5jZv2BC445
Maybe it's because there are no names for substances?

**Comment by hampos** [comment]
Yes you are right, the errors were related to #83 , It is now fixed and the datasets are displayed nicely. Image descriptors seem to work fine, the dataset with no selected descriptors is empty of columns.

**Comment by dphilip** [comment]
Very nice! 
A dataset with Image descriptors looks like this now:
http://test.jaqpot.org/data_detail?name=VkXe1gRwyRoO
