### ISSUE TITLE
Datasets with missing totalRows and totalColumns 

### ISSUE THREAD

**Issue by hampos** [KinkyDesign/JaqpotQuattroUI#78]
Cannot  be retrieved with NPE

**Comment by AValsamis** [comment]
Do we have to re-add the dataset.setTotalRows, dataset.setTotalColumns code snippet in DatasetHandler.find? New datasets are stored correctly but old ones, may need that code.

**Comment by hampos** [comment]
Yes lets just check if they don't exist and recalculate them on find().
