### ISSUE TITLE
readacross train a model does not work

### ISSUE THREAD

**Issue by gdrakakis** [KinkyDesign/JaqpotQuattroUI#79]
same error for every dataset 
![image](https://cloud.githubusercontent.com/assets/10755430/16840155/b8e961d0-49db-11e6-9ccc-22d7634d9324.png)

**Comment by AValsamis** [comment]
ReadAcross works for me at the moment while on desktop. At the same time it doesn't work from my mobile or from other PCs in office. Could that help us resolve it?

![readacross - 2016-07-20 17 20 00](https://cloud.githubusercontent.com/assets/11833882/16990660/72a88348-4ea1-11e6-847a-27045bfe7f30.png)

**Comment by gdrakakis** [comment]
can now select parameters but then fails

![image](https://cloud.githubusercontent.com/assets/10755430/17019463/1633e612-4f45-11e6-80af-0dcef007a816.png)
